version: "3.9"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8080"